=begin
#BitPesa Private API

#API specification used for internal BitPesa endpoints

OpenAPI spec version: 1.0

Generated by: https://openapi-generator.tech
OpenAPI Generator version: 4.0.0-beta3

=end

require 'spec_helper'
require 'json'

# Unit tests for TransferZero::BankAccountDetailsApi
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe 'BankAccountDetailsApi' do
  before do
    # run before each test
    @api_instance = TransferZero::BankAccountDetailsApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of BankAccountDetailsApi' do
    it 'should create an instance of BankAccountDetailsApi' do
      expect(@api_instance).to be_instance_of(TransferZero::BankAccountDetailsApi)
    end
  end

  # unit tests for get_bank_account_details
  # Fetching bank account details
  # Returns single bank account details based on the currency
  # @param currency Currency of the required bank account details.  Example: &#x60;/v1/bank_account_details/NGN&#x60;
  # @param [Hash] opts the optional parameters
  # @return [BankAccountDetailsResponse]
  describe 'get_bank_account_details test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
