=begin
#TransferZero API

#Reference documentation for the TransferZero API V1

OpenAPI spec version: 1.0

Generated by: https://openapi-generator.tech
OpenAPI Generator version: 4.0.0-beta3

=end

require 'spec_helper'
require 'json'

# Unit tests for TransferZero::DlocalBalanceApi
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe 'DlocalBalanceApi' do
  before do
    # run before each test
    @api_instance = TransferZero::DlocalBalanceApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of DlocalBalanceApi' do
    it 'should create an instance of DlocalBalanceApi' do
      expect(@api_instance).to be_instance_of(TransferZero::DlocalBalanceApi)
    end
  end

  # unit tests for get_balance
  # Get dlocal balances
  # This endpoint retrieves dlocal account balances
  # @param [Hash] opts the optional parameters
  # @return [DlocalBalanceResponse]
  describe 'get_balance test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
