=begin
#TransferZero API

#Reference documentation for the TransferZero API V1

OpenAPI spec version: 1.0

Generated by: https://openapi-generator.tech
OpenAPI Generator version: 4.0.0-beta3

=end

require 'spec_helper'
require 'json'

# Unit tests for TransferZero::PayinMethodsApi
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe 'PayinMethodsApi' do
  before do
    # run before each test
    @api_instance = TransferZero::PayinMethodsApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of PayinMethodsApi' do
    it 'should create an instance of PayinMethodsApi' do
      expect(@api_instance).to be_instance_of(TransferZero::PayinMethodsApi)
    end
  end

  # unit tests for delete_payin_method
  # Deleting a payin method
  # Initiates a cancellation request for the specified payin method
  # @param payin_method_id ID of the payin method to delete.  Example: &#x60;/v1/payin_methods/bf9ff782-e182-45ac-abea-5bce83ad6670&#x60;
  # @param [Hash] opts the optional parameters
  # @return [PayinMethodResponse]
  describe 'delete_payin_method test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for get_payin_method
  # Fetching a payin method
  # Show a payin method by id
  # @param payin_method_id ID of the payin method to get.  Example: &#x60;/v1/payin_methods/bf9ff782-e182-45ac-abea-5bce83ad6670&#x60;
  # @param [Hash] opts the optional parameters
  # @return [PayinMethodResponse]
  describe 'get_payin_method test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for patch_payin_method
  # Updating a payin method
  # Updates the payin method specified in the URL path.
  # @param payin_method_id ID of the payin method to get.  Example: &#x60;/v1/payin_methods/bf9ff782-e182-45ac-abea-5bce83ad6670&#x60;
  # @param payin_method 
  # @param [Hash] opts the optional parameters
  # @return [PayinMethodResponse]
  describe 'patch_payin_method test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for retry_payin_method
  # Retries PayinMethod
  # Retries the collection process for the payin method.  Please note only payin methods in &#x60;error&#x60; state can be retried.
  # @param payin_method_id ID of the payin method whose collection process should be retried  Example: &#x60;/v1/payin_methods/9d4d7b73-a94c-4979-ab57-09074fd55d33/retry&#x60;
  # @param [Hash] opts the optional parameters
  # @return [nil]
  describe 'retry_payin_method test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
