=begin
#BitPesa Private API

#API specification used for internal BitPesa endpoints

OpenAPI spec version: 1.0

Generated by: https://openapi-generator.tech
OpenAPI Generator version: 4.0.0-beta3

=end

require 'spec_helper'
require 'json'

# Unit tests for TransferZero::SenderDocumentsApi
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe 'SenderDocumentsApi' do
  before do
    # run before each test
    @api_instance = TransferZero::SenderDocumentsApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of SenderDocumentsApi' do
    it 'should create an instance of SenderDocumentsApi' do
      expect(@api_instance).to be_instance_of(TransferZero::SenderDocumentsApi)
    end
  end

  # unit tests for add_document_sender
  # Adding a document to a sender
  # Adds a new document to a sender 
  # @param sender_id ID of the sender to add the document.  Example: &#x60;/v1/senders/bf9ff782-e182-45ac-abea-5bce83ad6670/documents/26ec8517-2f0d-48c0-b74f-0bccb9ab3a87/add&#x60;
  # @param document_id The ID of the document to be added to the sender.  Example: &#x60;/v1/senders/bf9ff782-e182-45ac-abea-5bce83ad6670/documents/26ec8517-2f0d-48c0-b74f-0bccb9ab3a87/add&#x60;
  # @param [Hash] opts the optional parameters
  # @return [DocumentResponse]
  describe 'add_document_sender test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for get_sender_document
  # Fetching a document belonging to a sender
  # Returns a single document belonging to a sender by the Document ID
  # @param sender_id ID of the sender who owns the requested document.  Example: &#x60;/v1/senders/bf9ff782-e182-45ac-abea-5bce83ad6670/documents/26ec8517-2f0d-48c0-b74f-0bccb9ab3a87&#x60;
  # @param document_id ID of the document to get.  Example: &#x60;/v1/senders/bf9ff782-e182-45ac-abea-5bce83ad6670/documents/26ec8517-2f0d-48c0-b74f-0bccb9ab3a87&#x60;
  # @param [Hash] opts the optional parameters
  # @return [DocumentResponse]
  describe 'get_sender_document test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for get_sender_documents
  # Getting a list of documents belonging to a sender
  # Fetches a list of documents belonging to a sender.
  # @param sender_id ID of the sender who owns the requested documents.  Example: &#x60;/v1/senders/bf9ff782-e182-45ac-abea-5bce83ad6670/documents&#x60;
  # @param [Hash] opts the optional parameters
  # @option opts [Integer] :page The page number to request (defaults to 1)
  # @option opts [Integer] :per The number of results to load per page (defaults to 10)
  # @return [DocumentListResponse]
  describe 'get_sender_documents test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for remove_document_sender
  # Removing a document from a sender
  # Removes a document from a sender 
  # @param sender_id ID of the sender with the document to remove.  Example: &#x60;/v1/senders/bf9ff782-e182-45ac-abea-5bce83ad6670/documents/26ec8517-2f0d-48c0-b74f-0bccb9ab3a87/remove&#x60;
  # @param document_id The ID of the document to be removed from the sender.  Example: &#x60;/v1/senders/bf9ff782-e182-45ac-abea-5bce83ad6670/documents/26ec8517-2f0d-48c0-b74f-0bccb9ab3a87/remove&#x60;
  # @param [Hash] opts the optional parameters
  # @return [DocumentResponse]
  describe 'remove_document_sender test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
