=begin
#TransferZero API

#Reference documentation for the TransferZero API V1

The version of the OpenAPI document: 1.0

Generated by: https://openapi-generator.tech
OpenAPI Generator version: 4.1.1

=end

require 'spec_helper'
require 'json'
require 'date'

# Unit tests for TransferZero::DocumentWebhookAllOf
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe 'DocumentWebhookAllOf' do
  before do
    # run before each test
    @instance = TransferZero::DocumentWebhookAllOf.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of DocumentWebhookAllOf' do
    it 'should create an instance of DocumentWebhookAllOf' do
      expect(@instance).to be_instance_of(TransferZero::DocumentWebhookAllOf)
    end
  end
  describe 'test attribute "object"' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
