=begin
#BitPesa Private API

#API specification used for internal BitPesa endpoints

OpenAPI spec version: 1.0

Generated by: https://openapi-generator.tech
OpenAPI Generator version: 4.0.0-beta3

=end

require 'spec_helper'
require 'json'
require 'date'

# Unit tests for TransferZero::EntityRating
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe 'EntityRating' do
  before do
    # run before each test
    @instance = TransferZero::EntityRating.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of EntityRating' do
    it 'should create an instance of EntityRating' do
      expect(@instance).to be_instance_of(TransferZero::EntityRating)
    end
  end
end
