=begin
#TransferZero API

#Reference documentation for the TransferZero API V1

OpenAPI spec version: 1.0

Generated by: https://openapi-generator.tech
OpenAPI Generator version: 4.0.0-beta3

=end

require 'uri'

module TransferZero
  class MandatesApi
    attr_accessor :api_client

    def initialize(api_client = ApiClient.default)
      @api_client = api_client
    end


    # Fetch a single mandate
    # Finds and returns a Mandate created within the current calendar year, where the mandate is linked to a Recipient owned by the authenticated API key.  Returns 404 if the mandate is not owned by the API key or was not issued in the current calendar year — mandates are only valid for the year in which they were issued.
    # @param mandate_id ID of the mandate.  Example: &#x60;/v1/mandates/bf9ff782-e182-45ac-abea-5bce83ad6670&#x60;
    # @param [Hash] opts the optional parameters
    # @return [MandateResponse]
    def get_mandate(mandate_id, opts = {})
      data, _status_code, _headers = get_mandate_with_http_info(mandate_id, opts)
      data
    end

    # Fetch a single mandate
    # Finds and returns a Mandate created within the current calendar year, where the mandate is linked to a Recipient owned by the authenticated API key.  Returns 404 if the mandate is not owned by the API key or was not issued in the current calendar year — mandates are only valid for the year in which they were issued.
    # @param mandate_id ID of the mandate.  Example: &#x60;/v1/mandates/bf9ff782-e182-45ac-abea-5bce83ad6670&#x60;
    # @param [Hash] opts the optional parameters
    # @return [Array<(MandateResponse, Fixnum, Hash)>] MandateResponse data, response status code and response headers
    def get_mandate_with_http_info(mandate_id, opts = {})
      if @api_client.config.debugging
        @api_client.config.logger.debug 'Calling API: MandatesApi.get_mandate ...'
      end
      # verify the required parameter 'mandate_id' is set
      if @api_client.config.client_side_validation && mandate_id.nil?
        fail ArgumentError, "Missing the required parameter 'mandate_id' when calling MandatesApi.get_mandate"
      end
      # resource path
      local_var_path = '/mandates/{Mandate ID}'.sub('{' + 'Mandate ID' + '}', mandate_id.to_s)

      # query parameters
      query_params = {}

      # header parameters
      header_params = {}
      # HTTP header 'Accept' (if needed)
      header_params['Accept'] = @api_client.select_header_accept(['application/json'])

      # form parameters
      form_params = {}

      # http body (model)
      post_body = nil
      auth_names = ['AuthorizationKey', 'AuthorizationNonce', 'AuthorizationSecret', 'AuthorizationSignature']
      data, status_code, headers = @api_client.call_api(:GET, local_var_path,
        :header_params => header_params,
        :query_params => query_params,
        :form_params => form_params,
        :body => post_body,
        :auth_names => auth_names,
        :return_type => 'MandateResponse')
      if @api_client.config.debugging
        @api_client.config.logger.debug "API called: MandatesApi#get_mandate\nData: #{data.inspect}\nStatus code: #{status_code}\nHeaders: #{headers}"
      end
      return data, status_code, headers
    end
  end
end
