=begin
#BitPesa Private API

#API specification used for internal BitPesa endpoints

OpenAPI spec version: 1.0

Generated by: https://openapi-generator.tech
OpenAPI Generator version: 4.0.0-beta3

=end

require 'uri'

module TransferZero
  class OpenCorporatesSupportedCountriesApi
    attr_accessor :api_client

    def initialize(api_client = ApiClient.default)
      @api_client = api_client
    end


    # Get List of Supported Countries from OpenCorporates
    # Get List of Supported Countries from OpenCorporates
    # @param [Hash] opts the optional parameters
    # @return [OpenCorporatesSupportedCountriesListResponse]
    def get_open_corporates_supported_countries(opts = {})
      data, _status_code, _headers = get_open_corporates_supported_countries_with_http_info(opts)
      data
    end

    # Get List of Supported Countries from OpenCorporates
    # Get List of Supported Countries from OpenCorporates
    # @param [Hash] opts the optional parameters
    # @return [Array<(OpenCorporatesSupportedCountriesListResponse, Fixnum, Hash)>] OpenCorporatesSupportedCountriesListResponse data, response status code and response headers
    def get_open_corporates_supported_countries_with_http_info(opts = {})
      if @api_client.config.debugging
        @api_client.config.logger.debug 'Calling API: OpenCorporatesSupportedCountriesApi.get_open_corporates_supported_countries ...'
      end
      # resource path
      local_var_path = '/open_corporates/countries'

      # query parameters
      query_params = {}

      # header parameters
      header_params = {}
      # HTTP header 'Accept' (if needed)
      header_params['Accept'] = @api_client.select_header_accept(['application/json'])

      # form parameters
      form_params = {}

      # http body (model)
      post_body = nil
      auth_names = ['AuthorizationKey', 'AuthorizationNonce', 'AuthorizationSecret', 'AuthorizationSignature']
      data, status_code, headers = @api_client.call_api(:GET, local_var_path,
        :header_params => header_params,
        :query_params => query_params,
        :form_params => form_params,
        :body => post_body,
        :auth_names => auth_names,
        :return_type => 'OpenCorporatesSupportedCountriesListResponse')
      if @api_client.config.debugging
        @api_client.config.logger.debug "API called: OpenCorporatesSupportedCountriesApi#get_open_corporates_supported_countries\nData: #{data.inspect}\nStatus code: #{status_code}\nHeaders: #{headers}"
      end
      return data, status_code, headers
    end
  end
end
