=begin
#BitPesa Private API

#API specification used for internal BitPesa endpoints

OpenAPI spec version: 1.0

Generated by: https://openapi-generator.tech
OpenAPI Generator version: 4.0.0-beta3

=end

require 'date'

module TransferZero
class EntityRating
  
  EXTREMELY_HIGH = "extremely_high".freeze
  HIGH_RISK = "high_risk".freeze
  MEDIUM_RISK = "medium_risk".freeze
  LOW_RISK = "low_risk".freeze

  # Builds the enum from string
  # @param [String] The enum value in the form of the string
  # @return [String] The enum value
  def build_from_hash(value)
    constantValues = EntityRating.constants.select { |c| EntityRating::const_get(c) == value }
    raise "Invalid ENUM value #{value} for class #EntityRating" if constantValues.empty? && !value.empty?
    value
  end
end

end
