=begin
#TransferZero API

#Reference documentation for the TransferZero API V1

OpenAPI spec version: 1.0

Generated by: https://openapi-generator.tech
OpenAPI Generator version: 4.0.0-beta3

=end

require 'date'

module TransferZero
class PayoutMethodCountryEnum
  
  CI = "CI".freeze
  ML = "ML".freeze
  SN = "SN".freeze
  NG = "NG".freeze
  MA = "MA".freeze
  TZ = "TZ".freeze
  GH = "GH".freeze
  UG = "UG".freeze
  KE = "KE".freeze
  NJ = "NJ".freeze
  EU = "EU".freeze
  GB = "GB".freeze
  ZA = "ZA".freeze
  EG = "EG".freeze

  # Builds the enum from string
  # @param [String] The enum value in the form of the string
  # @return [String] The enum value
  def build_from_hash(value)
    constantValues = PayoutMethodCountryEnum.constants.select { |c| PayoutMethodCountryEnum::const_get(c) == value }
    raise "Invalid ENUM value #{value} for class #PayoutMethodCountryEnum" if constantValues.empty? && !value.empty?
    value
  end
end

end
