=begin
#TransferZero API

#Reference documentation for the TransferZero API V1

The version of the OpenAPI document: 1.0

Generated by: https://openapi-generator.tech
OpenAPI Generator version: 4.1.1

=end

require 'date'

module TransferZero
class PayoutMethodMobileProviderEnum
  
  ORANGE = "orange".freeze
  TIGO = "tigo".freeze
  MOOV = "moov".freeze
  MTN = "mtn".freeze
  AIRTEL = "airtel".freeze
  VODAFONE = "vodafone".freeze
  MPESA = "mpesa".freeze
  AFRICELL = "africell".freeze
  TELECOM = "telecom".freeze
  MOBICASH = "mobicash".freeze

  # Builds the enum from string
  # @param [String] The enum value in the form of the string
  # @return [String] The enum value
  def build_from_hash(value)
    constantValues = PayoutMethodMobileProviderEnum.constants.select { |c| PayoutMethodMobileProviderEnum::const_get(c) == value }
    raise "Invalid ENUM value #{value} for class #PayoutMethodMobileProviderEnum" if constantValues.empty? && !value.empty?
    value
  end
end

end
