=begin
#BitPesa Private API

#API specification used for internal BitPesa endpoints

OpenAPI spec version: 1.0

Generated by: https://openapi-generator.tech
OpenAPI Generator version: 4.0.0-beta3

=end

require 'date'

module TransferZero
# PIX Payment: ```JSON   \"details\": {     \"first_name\": \"First\",     \"last_name\": \"Last\",     \"city\": \"Brasilia\",     \"postal_code\": \"70070\",     \"phone_number\": \"+552112345678\", // E.164 international format     \"pix_key_type\": \"email\",     \"pix_key_value\": \"person@example.com\",     \"identity_card_type\": \"ID\",     \"identity_card_id\": \"01234567890\",     \"transfer_reason\": \"personal_account\"   } ```  TED Payment: ```JSON   \"details\": {     \"first_name\": \"First\",     \"last_name\": \"Last\",     \"city\": \"Brasilia\",     \"postal_code\": \"70070\",     \"phone_number\": \"+552112345678\", // E.164 international format     \"bank_code\": \"104\",     \"branch_code\": \"00001\",     \"bank_account\": \"0009795493\",     \"bank_account_type\": \"10\",     \"identity_card_type\": \"ID\",     \"identity_card_id\": \"01234567890\",     \"transfer_reason\": \"personal_account\"   } ```  See [BRL Bank](https://docs.transferzero.com/docs/payout-details/#brlbank) documentation for the bank_code and transfer_reason lists
class PayoutMethodDetailsBRLBank
  attr_accessor :first_name

  attr_accessor :last_name

  attr_accessor :city

  attr_accessor :postal_code

  attr_accessor :phone_number

  attr_accessor :bank_code

  attr_accessor :branch_code

  attr_accessor :bank_account

  attr_accessor :bank_account_type

  attr_accessor :pix_key_type

  attr_accessor :pix_key_value

  attr_accessor :identity_card_type

  attr_accessor :identity_card_id

  attr_accessor :transfer_reason

  # Attribute mapping from ruby-style variable name to JSON key.
  def self.attribute_map
    {
      :'first_name' => :'first_name',
      :'last_name' => :'last_name',
      :'city' => :'city',
      :'postal_code' => :'postal_code',
      :'phone_number' => :'phone_number',
      :'bank_code' => :'bank_code',
      :'branch_code' => :'branch_code',
      :'bank_account' => :'bank_account',
      :'bank_account_type' => :'bank_account_type',
      :'pix_key_type' => :'pix_key_type',
      :'pix_key_value' => :'pix_key_value',
      :'identity_card_type' => :'identity_card_type',
      :'identity_card_id' => :'identity_card_id',
      :'transfer_reason' => :'transfer_reason'
    }
  end

  # Attribute type mapping.
  def self.openapi_types
    {
      :'first_name' => :'String',
      :'last_name' => :'String',
      :'city' => :'String',
      :'postal_code' => :'String',
      :'phone_number' => :'String',
      :'bank_code' => :'String',
      :'branch_code' => :'String',
      :'bank_account' => :'String',
      :'bank_account_type' => :'PayoutMethodBankAccountTypeEnum',
      :'pix_key_type' => :'PayoutMethodPixKeyTypeEnum',
      :'pix_key_value' => :'String',
      :'identity_card_type' => :'PayoutMethodIdentityCardTypeEnum',
      :'identity_card_id' => :'String',
      :'transfer_reason' => :'PayoutMethodTransferReasonEnum'
    }
  end

  # Initializes the object
  # @param [Hash] attributes Model attributes in the form of hash
  def initialize(attributes = {})
    if (!attributes.is_a?(Hash))
      fail ArgumentError, "The input argument (attributes) must be a hash in `TransferZero::PayoutMethodDetailsBRLBank` initialize method"
    end

    # check to see if the attribute exists and convert string to symbol for hash key
    attributes = attributes.each_with_object({}) { |(k, v), h|
      if (!self.class.attribute_map.key?(k.to_sym))
        fail ArgumentError, "`#{k}` is not a valid attribute in `TransferZero::PayoutMethodDetailsBRLBank`. Please check the name to make sure it's valid. List of attributes: " + self.class.attribute_map.keys.inspect
      end
      h[k.to_sym] = v
    }

    if attributes.key?(:'first_name')
      self.first_name = attributes[:'first_name']
    end

    if attributes.key?(:'last_name')
      self.last_name = attributes[:'last_name']
    end

    if attributes.key?(:'city')
      self.city = attributes[:'city']
    end

    if attributes.key?(:'postal_code')
      self.postal_code = attributes[:'postal_code']
    end

    if attributes.key?(:'phone_number')
      self.phone_number = attributes[:'phone_number']
    end

    if attributes.key?(:'bank_code')
      self.bank_code = attributes[:'bank_code']
    end

    if attributes.key?(:'branch_code')
      self.branch_code = attributes[:'branch_code']
    end

    if attributes.key?(:'bank_account')
      self.bank_account = attributes[:'bank_account']
    end

    if attributes.key?(:'bank_account_type')
      self.bank_account_type = attributes[:'bank_account_type']
    end

    if attributes.key?(:'pix_key_type')
      self.pix_key_type = attributes[:'pix_key_type']
    end

    if attributes.key?(:'pix_key_value')
      self.pix_key_value = attributes[:'pix_key_value']
    end

    if attributes.key?(:'identity_card_type')
      self.identity_card_type = attributes[:'identity_card_type']
    end

    if attributes.key?(:'identity_card_id')
      self.identity_card_id = attributes[:'identity_card_id']
    end

    if attributes.key?(:'transfer_reason')
      self.transfer_reason = attributes[:'transfer_reason']
    end
  end

  # Show invalid properties with the reasons. Usually used together with valid?
  # @return Array for valid properties with the reasons
  def list_invalid_properties
    invalid_properties = Array.new
    if @first_name.nil?
      invalid_properties.push('invalid value for "first_name", first_name cannot be nil.')
    end

    if @last_name.nil?
      invalid_properties.push('invalid value for "last_name", last_name cannot be nil.')
    end

    if @city.nil?
      invalid_properties.push('invalid value for "city", city cannot be nil.')
    end

    if @postal_code.nil?
      invalid_properties.push('invalid value for "postal_code", postal_code cannot be nil.')
    end

    if @identity_card_type.nil?
      invalid_properties.push('invalid value for "identity_card_type", identity_card_type cannot be nil.')
    end

    if @identity_card_id.nil?
      invalid_properties.push('invalid value for "identity_card_id", identity_card_id cannot be nil.')
    end

    if @transfer_reason.nil?
      invalid_properties.push('invalid value for "transfer_reason", transfer_reason cannot be nil.')
    end

    invalid_properties
  end

  # Check to see if the all the properties in the model are valid
  # @return true if the model is valid
  def valid?
    return false if @first_name.nil?
    return false if @last_name.nil?
    return false if @city.nil?
    return false if @postal_code.nil?
    return false if @identity_card_type.nil?
    return false if @identity_card_id.nil?
    return false if @transfer_reason.nil?
    true
  end

  # Checks equality by comparing each attribute.
  # @param [Object] Object to be compared
  def ==(o)
    return true if self.equal?(o)
    self.class == o.class &&
        first_name == o.first_name &&
        last_name == o.last_name &&
        city == o.city &&
        postal_code == o.postal_code &&
        phone_number == o.phone_number &&
        bank_code == o.bank_code &&
        branch_code == o.branch_code &&
        bank_account == o.bank_account &&
        bank_account_type == o.bank_account_type &&
        pix_key_type == o.pix_key_type &&
        pix_key_value == o.pix_key_value &&
        identity_card_type == o.identity_card_type &&
        identity_card_id == o.identity_card_id &&
        transfer_reason == o.transfer_reason
  end

  # @see the `==` method
  # @param [Object] Object to be compared
  def eql?(o)
    self == o
  end

  # Calculates hash code according to all attributes.
  # @return [Integer] Hash code
  def hash
    [first_name, last_name, city, postal_code, phone_number, bank_code, branch_code, bank_account, bank_account_type, pix_key_type, pix_key_value, identity_card_type, identity_card_id, transfer_reason].hash
  end

require 'active_support/core_ext/hash'
require 'active_support/hash_with_indifferent_access.rb'
# Builds the object from hash
# @param [Hash] attributes Model attributes in the form of hash
# @return [Object] Returns the model itself
def build_from_hash(attributes)
  return nil unless attributes.is_a?(Hash)
  self.class.openapi_types.each_pair do |key, type|
    if type =~ /\AArray<(.*)>/i
      # check to ensure the input is an array given that the the attribute
      # is documented as an array but the input is not
      if attributes[self.class.attribute_map[key]].is_a?(Array)
        self.send("#{key}=", attributes[self.class.attribute_map[key]].map { |v| _deserialize($1, v) })
      end
    elsif !attributes[self.class.attribute_map[key]].nil?
      self.send("#{key}=", _deserialize(type, attributes[self.class.attribute_map[key]]))
    end # or else data not found in attributes(hash), not an issue as the data can be optional
  end

  self
end

# Deserializes the data based on type
# @param string type Data type
# @param string value Value to be deserialized
# @return [Object] Deserialized data
def _deserialize(type, value)
  case type.to_sym
  when :DateTime
    DateTime.parse(value)
  when :Date
    Date.parse(value)
  when :String
    value.to_s
  when :Integer
    value.to_i
  when :Float
    value.to_f
  when :Boolean
    if value.to_s =~ /\A(true|t|yes|y|1)\z/i
      true
    else
      false
    end
  when :Object
    # generic object (usually a Hash), return directly
    value
  when /\AArray<(?<inner_type>.+)>\z/
    inner_type = Regexp.last_match[:inner_type]
    value.map { |v| _deserialize(inner_type, v) }
  when /\AHash<(?<k_type>.+?), (?<v_type>.+)>\z/
    k_type = Regexp.last_match[:k_type]
    v_type = Regexp.last_match[:v_type]
    {}.tap do |hash|
      value.each do |k, v|
        hash[_deserialize(k_type, k)] = _deserialize(v_type, v)
      end
    end
  else # model
    temp_model = TransferZero.const_get(type).new
    temp_model.build_from_hash(value)
  end
end

# Returns the string representation of the object
# @return [String] String presentation of the object
def to_s
  to_hash.to_s
end

# to_body is an alias to to_hash (backward compatibility)
# @return [Hash] Returns the object in the form of hash
def to_body
  to_hash
end

# Returns the object in the form of hash
# @return [Hash] Returns the object in the form of hash
def to_hash
  hash = {}
  self.class.attribute_map.each_pair do |attr, param|
    value = self.send(attr)
    next if value.nil?
    hash[param] = _to_hash(value)
  end
  ::ActiveSupport::HashWithIndifferentAccess.new(hash)
end

def [](key)
  to_hash[key]
end

def dig(*args)
  to_hash.dig(*args)
end

# Outputs non-array value in the form of hash
# For object, use to_hash. Otherwise, just return the value
# @param [Object] value Any valid value
# @return [Hash] Returns the value in the form of hash
def _to_hash(value)
  if value.is_a?(Array)
    value.compact.map { |v| _to_hash(v) }
  elsif value.is_a?(Hash)
    {}.tap do |hash|
      value.each { |k, v| hash[k] = _to_hash(v) }
    end
  elsif value.respond_to? :to_hash
    value.to_hash
  else
    value
  end
end

end

end
