=begin
#TransferZero API

#Reference documentation for the TransferZero API V1

OpenAPI spec version: 1.0

Generated by: https://openapi-generator.tech
OpenAPI Generator version: 4.0.0-beta3

=end

require 'date'

module TransferZero
class PayoutMethodNatureOfBusinessEnum
  
  PERSONAL = "personal".freeze
  AGRICULTURE_AND_HUNTING = "agriculture_and_hunting".freeze
  FORESTRY = "forestry".freeze
  FISHING = "fishing".freeze
  AGRICULTURAL_BY_PRODUCTS = "agricultural_by_products".freeze
  COAL_MINING = "coal_mining".freeze
  OIL_MINING = "oil_mining".freeze
  IRON_ORE_MINING = "iron_ore_mining".freeze
  OTHER_METAL_AND_DIAMOND_MINING = "other_metal_and_diamond_mining".freeze
  OTHER_MINERAL_MINING = "other_mineral_mining".freeze
  MANUFACTURING_OF_FOOD_DRINK_TOBACCO = "manufacturing_of_food_drink_tobacco".freeze
  MANUFACTURING_OF_TEXTILES_LEATHER_FUR_FURNITURE = "manufacturing_of_textiles_leather_fur_furniture".freeze
  MANUFACTURE_OF_WOODEN_PRODUCTS_FURNITURE = "manufacture_of_wooden_products_furniture".freeze
  MANUFACTURE_OF_PAPER_PULP_ALLIED_PRODUCTS = "manufacture_of_paper_pulp_allied_products".freeze
  MANUFACTURE_OF_CHEMICALS_MEDICAL_PETROLEUM_RUBBER_PLASTIC_PRODUCTS = "manufacture_of_chemicals_medical_petroleum_rubber_plastic_products".freeze
  MANUFACTURE_OF_POTTERY_CHINA_GLASS_STONE = "manufacture_of_pottery_china_glass_stone".freeze
  MANUFACTURE_OF_IRON_STEEL_NON_FERROUS_METALS_BASIC_INDUSTRIES = "manufacture_of_iron_steel_non_ferrous_metals_basic_industries".freeze
  MANUFACTURE_OF_METAL_PRODUCTS_ELECTRICAL_AND_SCIENTIFIC_ENGINEERING = "manufacture_of_metal_products_electrical_and_scientific_engineering".freeze
  MANUFACTURE_OF_JEWELRY_MUSICAL_INSTRUMENTS_TOYS = "manufacture_of_jewelry_musical_instruments_toys".freeze
  ELECTRICITY_GAS_AND_WATER = "electricity_gas_and_water".freeze
  CONSTRUCTION = "construction".freeze
  WHOLESALE_TRADE = "wholesale_trade".freeze
  RETAIL_TRADE = "retail_trade".freeze
  CATERING_INCL_HOTELS = "catering_incl_hotels".freeze
  TRANSPORT_STORAGE = "transport_storage".freeze
  COMMUNICATIONS = "communications".freeze
  FINANCE_AND_HOLDING_COMPANIES = "finance_and_holding_companies".freeze
  INSURANCE = "insurance".freeze
  BUSINESS_SERVICES = "business_services".freeze
  REAL_ESTATE_DEVELOPMENT_INVESTMENT = "real_estate_development_investment".freeze
  CENTRAL_STATE_GOVERNMENTS = "central_state_governments".freeze
  COMMUNITY_SERVICES_DEFENCE_POLICE_PRISONS_ETC = "community_services_defence_police_prisons_etc".freeze
  SOCIAL_SERVICES_EDUCATION_HEALTH_CARE = "social_services_education_health_care".freeze
  PERSONAL_SERVICES_LEISURE_SERVICES = "personal_services_leisure_services".freeze
  PERSONAL_SERVICES_DOMESTIC_LAUNDRY_REPAIRS = "personal_services_domestic_laundry_repairs".freeze
  PERSONAL_SERVICES_EMBASSIES_INTERNATIONAL_ORGANISATIONS = "personal_services_embassies_international_organisations".freeze

  # Builds the enum from string
  # @param [String] The enum value in the form of the string
  # @return [String] The enum value
  def build_from_hash(value)
    constantValues = PayoutMethodNatureOfBusinessEnum.constants.select { |c| PayoutMethodNatureOfBusinessEnum::const_get(c) == value }
    raise "Invalid ENUM value #{value} for class #PayoutMethodNatureOfBusinessEnum" if constantValues.empty? && !value.empty?
    value
  end
end

end
