=begin
#TransferZero API

#Reference documentation for the TransferZero API V1

OpenAPI spec version: 1.0

Generated by: https://openapi-generator.tech
OpenAPI Generator version: 4.0.0-beta3

=end

require 'date'

module TransferZero
  class TransactionState
    INITIAL = "initial".freeze
    APPROVED = "approved".freeze
    PENDING = "pending".freeze
    RECEIVED = "received".freeze
    MISPAID = "mispaid".freeze
    MANUAL = "manual".freeze
    PAID = "paid".freeze
    CANCELED = "canceled".freeze
    REFUNDED = "refunded".freeze
    EXCEPTION = "exception".freeze

    # Builds the enum from string
    # @param [String] The enum value in the form of the string
    # @return [String] The enum value
    def self.build_from_hash(value)
      new.build_from_hash(value)
    end

    # Builds the enum from string
    # @param [String] The enum value in the form of the string
    # @return [String] The enum value
    def build_from_hash(value)
      constantValues = TransactionState.constants.select { |c| TransactionState::const_get(c) == value }
      raise "Invalid ENUM value #{value} for class #TransactionState" if constantValues.empty?
      value
    end
  end
end
