name: Release Gem

on:
  push:
    branches:
      - master
      - BTA-11168-ci-cd
  workflow_dispatch:

jobs:
  release-please:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.2.2

      - run: bundle install

      - name: Publish the gem
        run: |
          mkdir -p $HOME/.gem
          touch $HOME/.gem/credentials
          chmod 0600 $HOME/.gem/credentials
          printf -- "---\n:rubygems_api_key: ${GEM_HOST_API_KEY}\n" > $HOME/.gem/credentials
          gem build *.gemspec
          gem push *.gem
        env:
          GEM_HOST_API_KEY: "${{secrets.GH_RELEASER_RUBYGEMS_API_KEY}}"

      - name: Tag the release
        run: |
          NEXT_TAG=$(awk '/VERSION/{print $3}' lib/transferzero-sdk/version.rb)
          git tag $NEXT_TAG
          git push --tags
